# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

cache: pip

matrix:
  include:
    # - python: 2.7
    #   env: TOXENV=py27
    # - python: 3.5
    #   env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37

install:
  # - pip install -r requirements.txt
  - pip install tox codecov
  - pip list

script: tox --sitepackages

after_success: codecov
